name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/resume@v1
        with:
          args: deploy --only hosting
          firebase_token: ${{ secrets.FIREKEY }}
